byu-is-software-design-concepts/winter-2020

- hw2/_submissions/olson-caleb/fizz-buzz/1-TEMPLATE.js
- hw2/_submissions/olson-caleb/fizz-buzz/README.md
- hw2/_submissions/olson-caleb/string-calculator/1-TEMPLATE.js
- hw2/_submissions/olson-caleb/string-calculator/README.md
For FizzBuzz, I check to see if the number is divisible by 3, 5, both, or neither, and then return the appropriate value. For the string calculator, I parsed the string into a array splitting on the commas, then determined the number of values in the array, and either converted the string to a number to add them together, or return the inputted number or 0.
> finished hw2

- hw2/_submissions/zwingli-alex/fizz-buzz/1-TEMPLATE.js
- hw2/_submissions/zwingli-alex/string-calculator/1-TEMPLATE.js
- I used the mod operator to determine if the numbers were multiples of 3 or 5
- I used the split operator to get a list of the numbers and iterated through the array to add them together
> Finished exercises

- hw2/_submissions/Smith-Statler/fizz-buzz.js
- hw2/_submissions/Smith-Statler/string-calbulator.js
For Fizz Buzz, I used the modulus operator to determine if the number was a multiple of 3 or 5. I then changed the output based on that determination.
For String calculator, I split the input string into each character. For each character, I determined if the value could be changed to a number. If it was possible, I added that number to a total and returned the total.
> Statler Smith HW2 Submission

- hw2/_submissions/adams-kyle/fizz-buzz/1-TEMPLATE.js
- hw2/_submissions/adams-kyle/fizz-buzz/README.md
- hw2/_submissions/adams-kyle/string-calculator/1-TEMPLATE.js
- hw2/_submissions/adams-kyle/string-calculator/README.md
The FizzBuzz one seemed pretty straight forward and I solved it immediately. The StringCalculator took longer because I first tried to use regex before realizing I could just look for the commas and split the string up into an array to work with.
Also, when is it better to fork repos vs clone? I thought that since it wasn't mine and I'm just contributing a small part that it might be better, but I notice nobody else seemed to do that.
> create StringCalculator and FizzBuzz

- hw2/_submissions/moore-christian/fizz-1-TEMPLATE.js
- hw2/_submissions/moore-christian/string-1-TEMPLATE.js
For the Fizz Buzz HW I just mod'd the input number by 3 and 5. I then just had an if statement which returned the appropriate response based off of my isFizz and isBuzz variables.
For the string HW I simply looped through all the chars in the string and if a char returned a truthy value after going through the parseInt() method, I added it to a running total which was returned at the end.
> Completed HW 2

- hw2/_submissions/parr-josh/fizz-buzz/1-TEMPLATE.js
- hw2/_submissions/parr-josh/fizz-buzz/README.md
- hw2/_submissions/parr-josh/string-calculator/1-TEMPLATE.js
- hw2/_submissions/parr-josh/string-calculator/README.md
FizzBuzz
- Used if statements to determine the number multiplicity
String Calculator
- Put the num into an array and split it on the comma and summed the inputs in a for loop
> HW2 Josh Parr

- hw2/_submissions/Gardner-Matthew/fizz-buzz/1-TEMPLATE.js
- hw2/_submissions/Gardner-Matthew/fizz-buzz/README.md
- hw2/_submissions/Gardner-Matthew/string-calculator/1-TEMPLATE.js
- hw2/_submissions/Gardner-Matthew/string-calculator/README.md
I think I did a poor job on the string calculator. I'd love to see a better way.
> HW 2 Solutions (probably not the best way to code them, but whatever.)

- hw2/_submissions/bawden-alec/fizz-buzz/1-TEMPLATE.js
- hw2/_submissions/bawden-alec/fizz-buzz/README.md
- hw2/_submissions/bawden-alec/string-calculator/1-TEMPLATE.js
- hw2/_submissions/bawden-alec/string-calculator/README.md
For Fizz Buzz
Used an if else statement to check module values for 3,5, or 3&5
For StringCalculator
Used a split function to save the string to an array and iterated through the array adding the values.
> Alec Bawden HW 2 

- hw2/_submissions/haddad-demitri/fizz-buzz/1-TEMPLATE.js
- hw2/_submissions/haddad-demitri/fizz-buzz/README.md
- hw2/_submissions/haddad-demitri/string-calculator/1-TEMPLATE.js
- hw2/_submissions/haddad-demitri/string-calculator/README.md
Solved Fizz Buzz using the mod function starting with numbers that are both multiples of 3 and 5. 
Solved String calculator using by parsing the int and adding it to an array while converting it to a number.
> Demitri Haddad hw2

- hw2/_submissions/haines-josh/fizz-buzz1-TEMPLATE.js
- hw2/_submissions/haines-josh/string-calculator1-TEMPLATE.js
Check it out. I am a git master. 
I solved the fizz buzz using my carbonated brain. An if else statement seemed best suited for the job.
The string calculator was a little bit more tricky. I looked a few of the other submissions for ideas. That is when I figured out there were instructions for these exercises in a files called README. Developer people should really consider naming those files to Read_This_Before_Coding. That would make it more clear.
> I can commit things with git!

- hw2/_submissions/Dalling-McKay/1-TEMPLATE-Dalling-McKay.js
- hw2/_submissions/Dalling-McKay/2-TEMPLATE-Dalling-McKay.js
FizzBuzz code was modified to check if num is divisible by 3, then 5. It dynamically adds the strings together based on the conditions. If the number isn't divisible by 3 or 5, it just shows the number.
The string connector splices the string by comma and creates an array of numbers. Then a for loop grabs all the values and totals them. I think there's a way to do it using some sort of array function, but I'm not familiar with it in js.
> Dalling-McKay

- hw2/_submissions/hola-jacob/fizz-buzz/1-TEMPLATE.js
- hw2/_submissions/hola-jacob/fizz-buzz/README.md
- hw2/_submissions/hola-jacob/string-calculator/1-TEMPLATE.js
- hw2/_submissions/hola-jacob/string-calculator/README.md
FizzBuzz: I used  'if' statements with modulus because it was simple
String-calculator:  I split the numbers on the ',' to put the numbers into an array. Then a for loop checks the numbers and then converts the strings to numbers.  I assumed that if people were to input more numbers (and they all were separated by commas) that the split function was most appropriate.
> Jacob Hola finished hw 2

- hw2/_submissions/Mcleod-Christopher/fizz-buzz/1-TEMPLATE.js
- hw2/_submissions/Mcleod-Christopher/fizz-buzz/README.md
- hw2/_submissions/Mcleod-Christopher/string-calculator/1-TEMPLATE.js
- hw2/_submissions/Mcleod-Christopher/string-calculator/README.md
For the FizzBuzz assignment, I just made an if statement that checked to see is the remainder of the number compared to 3 & 5 and then just 3 and just 5 to see if the number was a multiple then just changed the outcome based on the result.
For the string calculator, I split the string and used the map method to turn the result into integers. Then with the array of integers, I used the reduce method to call a function that added the array together which gave me the result that I needed.
> Christopher McLeod Hw2

- hw2/_submissions/poulson-gage/fizz-buzz/1-TEMPLATE.js
- hw2/_submissions/poulson-gage/fizz-buzz/README.md
- hw2/_submissions/poulson-gage/string-calculator/1-TEMPLATE.js
- hw2/_submissions/poulson-gage/string-calculator/README.md
for fizz buzz I used an if and several else if statements to check if it as a multiple of 3 and/or 5 by using modulus %.
For string calculator I created an array of numbers, iterated through each character in the string and check to see if it matched any numbers in my array. If it matched I added it into a results variable.
> i finished hw2

- hw2/_submissions/magill-dallen/FizzBuzzTemplate.js
- hw2/_submissions/magill-dallen/stringcalctemplate.js
For fizzbuzz I used the modulo in the if statement to see if the number was a multiple of 3 & 5, 3, 5, or neither.
For stringcalc, I used an if statement to determine if the input was empty, if the length was 1, and if it was anything other than that.  If it was other, I turned the input into an array of integers using split and added them together to produce the sum and output that sum.
> Completed HW2

- hw2/_submissions/hill-elayne/fizz-buzz.js
- hw2/_submissions/hill-elayne/string-calculator.js
fizz-buzz: used conditionals and the modulus operator to find multiples and outputted string based on result.
string-calculator: if empty string, return 0. Else, parse string into array by comma, and I used a simple for loop to sum the array.
> Elayne Hill completed hw2

- hw2/_submissions/Graham-William/1-TEMPLATE.js
- hw2/_submissions/Graham-William/2-TEMPLATE.js
Not sure if I'm doing this right. Here is the description for my solutions:
String Calculator:
I parsed the string and converted it into an array of numbers. I then looped through the numbers and added them up.
FizzBizz:
I essentially just used the modulus operator to test each number's divisibility with various "if" statements.
> Will Graham's Files

- hw2/_submissions/coleman-bailey/fizz-buzz.js
- hw2/_submissions/coleman-bailey/string-calculator.js
For fizz-buzz I did an if/else statement to check if the number was divisible by both 3 and 5, in which case return FizzBuzz. If the number was divisible by 3 then it would return Fizz and if it was divisible by 5 return Buzz.
For the string calculator I created a list, separated by commas and then looped through each element in the list with a for-each. Then for each element in the list summed them together.
> Finished the exercises

- hw2/_submissions/fankhauser-sarah/fizz-buzz.js
- hw2/_submissions/fankhauser-sarah/string-calculator.js
FizzBuzz -- I chose to condense the if statements into the conditional operator
String-Calculator -- If the string wasn't empty, I saved the numbers to an array and used the reduce method and a lambda function to add the numbers
> HW2 - Sarah Fankhauser

- hw2/_submissions/stark-jared/fizz-buzz.js
- hw2/_submissions/stark-jared/string-calculator.js
I went through and solved each exercise, trying to use the simplest and most straightforward logic I could.
> Solved my exercises

- hw2/_submissions/matheson-mckay/fizz-buzz/1-TEMPLATE.js
- hw2/_submissions/matheson-mckay/fizz-buzz/README.md
- hw2/_submissions/matheson-mckay/string-calculator/1-TEMPLATE.js
- hw2/_submissions/matheson-mckay/string-calculator/README.md
Completed Fizz-buzz and String-calculator. I copied and pasted my code from my branch on Patrik Drean's old is-693r repo since I already had done the exercises at that point before this new repo was created.
> Completed HW2 Exercises

- hw2/_submissions/merkley-connor/fizzbuzz.js
- hw2/_submissions/merkley-connor/string-calculator.js
I used the modulus operator and conditional statements for FizzBuzz. As for the string-calculator, I parsed the string values into an array and used a for loop to add the elements of the array.
> Connor Merkley HW2 Finished

- hw2/_submissions/nelson-colby/fizz-buzz/1-TEMPLATE.js
- hw2/_submissions/nelson-colby/fizz-buzz/README.md
- hw2/_submissions/nelson-colby/string-calculator/1-TEMPLATE.js
- hw2/_submissions/nelson-colby/string-calculator/README.md
For the FizzBuzz exercise, the solution uses the mod operator to check if the number passed into the function is divisible by 3. If so, it also checks if the number is divisible by 5. If the number is divisible by both 5 and 3, the function returns 'FizzBuzz'. If it is divisible by 3, but not by 5, the function returns 'Fizz'. If the number is divisible by 5, but not by 3, the function returns 'Buzz". If the number does not meet any of these conditions, the function returns the number as originally passed into the function.
For the StringCalculator exercise, the function first uses the 'split' function based on commas to create an array of the input's individual numbers. The function also checks that a maximum of two elements were added to the array from the string. Next, a 'sum' variable …
> Colby Nelson - HW2

- hw2/_submissions/Jung-Hoyong/fizz-buzz.js
- hw2/_submissions/Jung-Hoyong/string-calculator.js
This commit will add solutions to fizz-buzz and stingCalculator problems. For fizz-buzz, it will print 'Fizz' when num % 3 === 0, 'Buzz' when num % 5 === 0, and 'Fizz-Buzz' when num % 15 === 0. For StringCalculator, I split the string with a comma then loop through the array to add the numbers inside of the array.
> Solve fizz-buzz and stringCalculator problems

- hw2/_submissions/bird-savannah/1-TEMPLATE.js
- hw2/_submissions/bird-savannah/string-calculator.js
I tried to make it as simple as possible. If statements for each test run
> completed both practices

- hw2/_submissions/mahe-nicholas/fizz-buzz/fizzbuzz.js
- hw2/_submissions/mahe-nicholas/string-calculator/1-TEMPLATE.js
The key to the fizzbuzz problem was a few conditionals and using mod operators. For the string calculator, aside from the base case of an empty string, a forEach function worked fine to sequentially add the parsed values to an initialized variable
> solving exercises

- hw2/_submissions/white-isaac/fizz-buzz/1-TEMPLATE.js
- hw2/_submissions/white-isaac/fizz-buzz/README.md
- hw2/_submissions/white-isaac/string-calculator/1-TEMPLATE.js
- hw2/_submissions/white-isaac/string-calculator/README.md
FizzBuzz
- If the function receives a number that is divisible by 3 and 5 it will return FizzBuzz. Otherwise, if the number is just a multiple of 3 it will return Fizz and if it is just a multiple of 5 it will return Buzz. If none of the above conditions are met, it will just return the original number.
String Calculator
- The function gets the index of the comma in the string. If there is no comma, then the index will be -1.
- If there is a comma after the first position, then there were two numbers passed in. The function will separate the two numbers and add them together.
- If there is no comma after the first position, then there is only one number (or an empty string), this is then converted to an int and returned as the answer. ("" converted to an int is zero)
> HW2 Isaac White - Fizz-buzz and string-calculator

- hw2/_submissions/hayden-aaron/fizz-buzz/1-TEMPLATE.js
- hw2/_submissions/hayden-aaron/fizz-buzz/README.md
- hw2/_submissions/hayden-aaron/string-calculator/1-TEMPLATE.js
- hw2/_submissions/hayden-aaron/string-calculator/README.md
1. Frizz-buzz: I simply had a conditional in order to check if the number was divisible by 3, 5, or 3 and 5. I used a modulus in as the condition.
2. String calculator: I declared my variables at the beginning. Then I set the return result to 0 if nothing but an empty string was passed in. Otherwise, I split the string into an array, then mapped that array into another array that was integers, and last I used a for loop to add each element of the 2nd array to a total and then returned the total.
> HW2 - Aaron Hayden

- hw2/_submissions/Fitzgerald-Spencer/fizz-buzz/1-TEMPLATE.js
- hw2/_submissions/Fitzgerald-Spencer/fizz-buzz/README.md
- hw2/_submissions/Fitzgerald-Spencer/string-calculator/1-TEMPLATE.js
- hw2/_submissions/Fitzgerald-Spencer/string-calculator/README.md
I used the modulus operator (%) for the fizzbuzz examples and the split operator for strings to solve the string calculator problem.
> HW2: Submission - Fitzgerald, Spencer

- hw3/_submissions/hsu-haijung/big-o.js
- hw3/_submissions/hsu-haijung/persistence.js
- hw4/_submissions/hsu-haijung/unique-order/README.md
- hw4/_submissions/hsu-haijung/unique-order/babel.config.js
- hw4/_submissions/hsu-haijung/unique-order/package-lock.json
- hw4/_submissions/hsu-haijung/unique-order/package.json
- hw4/_submissions/hsu-haijung/unique-order/src/unique-order.js
- hw4/_submissions/hsu-haijung/unique-order/src/unique-order.test.js
- hw4/_submissions/hsu-haijung/zeroes/README.md
- hw4/_submissions/hsu-haijung/zeroes/babel.config.js
- hw4/_submissions/hsu-haijung/zeroes/package-lock.json
- hw4/_submissions/hsu-haijung/zeroes/package.json
- hw4/_submissions/hsu-haijung/zeroes/src/zeroes.js
- hw4/_submissions/hsu-haijung/zeroes/src/zeroes.test.js
> hw4 hsu-haijung

- hw3/_submissions/adams-kyle/big-o.js
- hw3/_submissions/adams-kyle/persistence.js
I didn't see the update Tyler sent to become an owner of this repo again so that's why this is a bit late pushing up. After I found that email to accept ownership it just finally went through
> retesting new SSH

- hw3/_submissions/mollinet-kyle/big-o-problem.js
- hw3/_submissions/mollinet-kyle/persistence.js
I hope this is what you're looking for! It got a little crazy in there for a bit. Tried to feed the baby while doing this homework. That amount of pressure should be applied in EVERY interview scenario ;)
> Mollinet kyle

- hw3/_submissions/smith-statler/big-o-problems.js
- hw3/_submissions/smith-statler/persistence.js
I evaluated the Big O functions based on the inputs and the processing.
For persistence, I used multiplications of 10 to separate out the input number into the digits. I then multiplied the digits together to generate a new number that I performed the same processing on. I did this until the new number was only one digit. I recorded the number of iterations I went through and returned that result.
> Statler Smith HW3

- hw3/_submissions/white-isaac/big-o/1-TEMPLATE.js
- hw3/_submissions/white-isaac/big-o/README.md
- hw3/_submissions/white-isaac/instructions.md
- hw3/_submissions/white-isaac/persistence/1-TEMPLATE.js
- hw3/_submissions/white-isaac/persistence/README.md
I did two variations of the persistence problem. I also went through and commented the big O notation of the various functions in the big-o section.
> White-Isaac -> Finished HW3

- hw3/_submissions/Mcleod-Christopher/big-o/1-TEMPLATE.js
- hw3/_submissions/Mcleod-Christopher/big-o/README.md
- hw3/_submissions/Mcleod-Christopher/persistence/1-TEMPLATE.js
- hw3/_submissions/Mcleod-Christopher/persistence/README.md
I worked through the Big-O Notation problems and then took a little while to work my way to a decent solution in the Coding exercise. I eventually was able to use a while loop to keep multiplying the numbers until they were less than 9. Inside the loop, I used the toString, split and reduce methods to multiply the numbers together while incrementing the times variable each time. It ended up being pretty concise and I was very happy with it.
> Christopher McLeod Hw3 Done!

- hw3/_submissions/hola-jacob/big-o/1-TEMPLATE.js
- hw3/_submissions/hola-jacob/persistence/1-TEMPLATE.js
Big O: I was not sure about a few of them so I had to look at the answer key and watch the youtube videos
Persistence: I know that it isn't the most amazing code, but it was where I am at right now and the other solutions are nice to see other ways of doing things.
> Jacob Hola finished HW3

- hw3/_submissions/Madsen-Peter/big-o-problems.js
- hw3/_submissions/Madsen-Peter/persistence.js
I've completed HW3 with comments briefly explaining my answers.
> Peter Madsen completed HW3

- hw3/_submissions/stennett-jordan/big-o.js
- hw3/_submissions/stennett-jordan/persistence.js
I "calculated" the big O of each of the example functions by looking for common patterns that indicate each of the algorithm's time complexity.
I used a recursive approach to solving the coding challenge. This approach was more or less a brute force approach but I was unable to think of a more elegant solution.
> Finish HW3

- hw3/_submissions/poulson-gage/big-o/1-TEMPLATE.js
- hw3/_submissions/poulson-gage/big-o/README.md
- hw3/_submissions/poulson-gage/persistence/1-TEMPLATE.js
- hw3/_submissions/poulson-gage/persistence/README.md
Honeslty the Big O still does not make a lot of sense but I think I figured them all out except the fibonnacci one.
For the persistence I was able to use a while loop to keep doing iterations until the string had a length of one.
> HW3 Commit

- hw2/_submissions/Graham-William/1-TEMPLATE.js
- hw2/_submissions/Graham-William/2-TEMPLATE.js
- hw3/_submissions/Graham-William/big0problems.js
HW3 stuff. I got a little mixed up with the branch, so I hope this uploads right.
> Graham william

- hw3/_submissions/fankhauser-sarah/big-o.js
- hw3/_submissions/fankhauser-sarah/persistence.js
tried to explain my thinking in the persistence problem and big-o practice
> sarah fankhauser -- hw3

- hw2/_submissions/marshall-zach/fizz-buzz.js
- hw2/_submissions/marshall-zach/string-calc.js
- hw3/_submissions/marshall-zach/big-o.js
- hw3/_submissions/marshall-zach/persistence.js
> Marshall zach

- hw2/_submissions/Jung-Hoyong/fizz-buzz.js
- hw2/_submissions/Jung-Hoyong/string-calculator.js
- hw3/_submissions/jung-hoyong/big-o.js
- hw3/_submissions/jung-hoyong/persistence.js
This commit will add a file in the submission folder under my name. I add answers with descriptions on big-o and persistence files.
I learned .reduce() function by doing the persistence assignment.
I will create a new branch to make a PR in the future.
> Hoyong Jung hw3

- hw3/_submissions/nelson-colby/big-o.js
- hw3/_submissions/nelson-colby/persistence.js
Finished Big-O and Persistence HW3 assignments with comments in code
> Finished hw3 submissions with comments describing my changes

- hw2/_submissions/Pixton-Parker/fizz-buzz.js
- hw2/_submissions/Pixton-Parker/string-calc.js
- hw3/_submissions/Pixton-Parker/big-O.js
- hw3/_submissions/Pixton-Parker/persistence.js
> Pixton parker

- hw2/_submissions/Ward-Candice/fizz-buzz/1-TEMPLATE.js
- hw2/_submissions/Ward-Candice/fizz-buzz/README.md
- hw2/_submissions/Ward-Candice/string-calculator/1-TEMPLATE.js
- hw2/_submissions/Ward-Candice/string-calculator/README.md
- hw3/_submissions/Ward-Candice/big-o/1-TEMPLATE.js
- hw3/_submissions/Ward-Candice/big-o/README.md
- hw3/_submissions/Ward-Candice/persistence/1-TEMPLATE.js
- hw3/_submissions/Ward-Candice/persistence/README.md
> Homework 2 and 3

- hw4/_submissions/nelson-colby/unique-order/README.md
- hw4/_submissions/nelson-colby/unique-order/babel.config.js
- hw4/_submissions/nelson-colby/unique-order/package-lock.json
- hw4/_submissions/nelson-colby/unique-order/package.json
- hw4/_submissions/nelson-colby/unique-order/src/unique-order.js
- hw4/_submissions/nelson-colby/unique-order/src/unique-order.test.js
- hw4/_submissions/nelson-colby/zeroes/README.md
- hw4/_submissions/nelson-colby/zeroes/babel.config.js
- hw4/_submissions/nelson-colby/zeroes/package-lock.json
- hw4/_submissions/nelson-colby/zeroes/package.json
- hw4/_submissions/nelson-colby/zeroes/src/zeroes.js
- hw4/_submissions/nelson-colby/zeroes/src/zeroes.test.js
I finished HW4 with tests and solutions for the unique-order and zeroes katas. Explanations of the code can be found with the tests and the comments.
> Finished HW4

- hw4/_submissions/smith-statler/unique-order/README.md
- hw4/_submissions/smith-statler/unique-order/babel.config.js
- hw4/_submissions/smith-statler/unique-order/package-lock.json
- hw4/_submissions/smith-statler/unique-order/package.json
- hw4/_submissions/smith-statler/unique-order/src/unique-order.js
- hw4/_submissions/smith-statler/unique-order/src/unique-order.test.js
- hw4/_submissions/smith-statler/zeroes/README.md
- hw4/_submissions/smith-statler/zeroes/babel.config.js
- hw4/_submissions/smith-statler/zeroes/package-lock.json
- hw4/_submissions/smith-statler/zeroes/package.json
- hw4/_submissions/smith-statler/zeroes/src/zeroes.js
- hw4/_submissions/smith-statler/zeroes/src/zeroes.test.js
I added some tests and solved the problems.
For unique-order, I created tests that tested if each letter in a string was unique and returned the unique letters. 
For zeroes, I created tests and a function that received an array of values, found each zero in the array, and moved the zeroes to the end.
> Statler Smith HW 4

- hw4/_submissions/thayne-josh/unique-order/src/unique-order.js
- hw4/_submissions/thayne-josh/zeroes/src/zeroes.js
Finished unique-order and zeroes
for unique order, I looped through each character in the string and compared it with the next character. If they weren't equal, then I pushed the character to a the result array
for zeroes, I looped through the array. If I found a zero, I popped it off
> Josh Thayne finished hw4

- hw4/_submissions/coleman-bailey/package-lock.json
- hw4/_submissions/coleman-bailey/unique-order/README.md
- hw4/_submissions/coleman-bailey/unique-order/babel.config.js
- hw4/_submissions/coleman-bailey/unique-order/package-lock.json
- hw4/_submissions/coleman-bailey/unique-order/package.json
- hw4/_submissions/coleman-bailey/unique-order/src/unique-order.js
- hw4/_submissions/coleman-bailey/unique-order/src/unique-order.test.js
- hw4/_submissions/coleman-bailey/zeroes/README.md
- hw4/_submissions/coleman-bailey/zeroes/babel.config.js
- hw4/_submissions/coleman-bailey/zeroes/package-lock.json
- hw4/_submissions/coleman-bailey/zeroes/package.json
- hw4/_submissions/coleman-bailey/zeroes/src/zeroes.js
- hw4/_submissions/coleman-bailey/zeroes/src/zeroes.test.js
- hw5/_submissions/coleman_bailey/mumbling/README.md
- hw5/_submissions/coleman_bailey/mumbling/babel.config.js
- hw5/_submissions/coleman_bailey/mumbling/package-lock.json
- hw5/_submissions/coleman_bailey/mumbling/package.json
- hw5/_submissions/coleman_bailey/mumbling/src/mumbling.js
- hw5/_submissions/coleman_bailey/mumbling/src/mumbling.test.js
- hw5/_submissions/coleman_bailey/package-lock.json
- hw5/_submissions/coleman_bailey/scramblies/README.md
- hw5/_submissions/coleman_bailey/scramblies/babel.config.js
- hw5/_submissions/coleman_bailey/scramblies/package-lock.json
- hw5/_submissions/coleman_bailey/scramblies/package.json
- hw5/_submissions/coleman_bailey/scramblies/src/scramblies.js
- hw5/_submissions/coleman_bailey/scramblies/src/scramblies.test.js
For the unique order function I used an array. I did the two suggested tests, one that each letter of a string and the other that test duplicating letters.
For the zeros exercise I did similarly. With the two suggested tests of multiple types and multiple zeros.
> Coleman bailey

- hw4/_submissions/Mcleod-Christopher/unique-order/README.md
- hw4/_submissions/Mcleod-Christopher/unique-order/babel.config.js
- hw4/_submissions/Mcleod-Christopher/unique-order/package-lock.json
- hw4/_submissions/Mcleod-Christopher/unique-order/package.json
- hw4/_submissions/Mcleod-Christopher/unique-order/src/unique-order.js
- hw4/_submissions/Mcleod-Christopher/unique-order/src/unique-order.test.js
- hw4/_submissions/Mcleod-Christopher/zeroes/README.md
- hw4/_submissions/Mcleod-Christopher/zeroes/babel.config.js
- hw4/_submissions/Mcleod-Christopher/zeroes/package-lock.json
- hw4/_submissions/Mcleod-Christopher/zeroes/package.json
- hw4/_submissions/Mcleod-Christopher/zeroes/src/zeroes.js
- hw4/_submissions/Mcleod-Christopher/zeroes/src/zeroes.test.js
In the Zeroes exercise, I just found and removed all the zeroes in the array by looping through the elements and if it was a zero then it was spliced from the array. Then I kept a count of the number of zeros and pushed that many on to the end of the array.
In the unique order exercise, I created a Set out of the split string. Sets by default cannot have duplicate values so all the duplicates were removed. Then I just converted the set into an array to return it as an array.
> Christopher McLeod hw4 done!

- hw6/_submissions/madsen-peter/fibonacci/README.md
- hw6/_submissions/madsen-peter/fibonacci/babel.config.js
- hw6/_submissions/madsen-peter/fibonacci/package-lock.json
- hw6/_submissions/madsen-peter/fibonacci/package.json
- hw6/_submissions/madsen-peter/fibonacci/src/fibonacci.js
- hw6/_submissions/madsen-peter/fibonacci/src/fibonacci.test.js
- hw6/_submissions/madsen-peter/spinning/README.md
- hw6/_submissions/madsen-peter/spinning/babel.config.js
- hw6/_submissions/madsen-peter/spinning/package-lock.json
- hw6/_submissions/madsen-peter/spinning/package.json
- hw6/_submissions/madsen-peter/spinning/src/spinning.js
- hw6/_submissions/madsen-peter/spinning/src/spinning.test.js
> Peter Madsen completed HW6

- hw6/_submissions/white-isaac/fibonacci/README.md
- hw6/_submissions/white-isaac/fibonacci/babel.config.js
- hw6/_submissions/white-isaac/fibonacci/package-lock.json
- hw6/_submissions/white-isaac/fibonacci/package.json
- hw6/_submissions/white-isaac/fibonacci/src/fibonacci.js
- hw6/_submissions/white-isaac/fibonacci/src/fibonacci.test.js
- hw6/_submissions/white-isaac/spinning/README.md
- hw6/_submissions/white-isaac/spinning/babel.config.js
- hw6/_submissions/white-isaac/spinning/package-lock.json
- hw6/_submissions/white-isaac/spinning/package.json
- hw6/_submissions/white-isaac/spinning/src/spinning.js
- hw6/_submissions/white-isaac/spinning/src/spinning.test.js
I completed and tested the programs to calculate a specific Fibonacci number and to spin words in a string that were at least 5 characters long.
> Whit- isaac-hw6

- hw6/_submissions/jung-hoyong/fibonacci/6-TEMPLATE/README.md
- hw6/_submissions/jung-hoyong/fibonacci/6-TEMPLATE/babel.config.js
- hw6/_submissions/jung-hoyong/fibonacci/6-TEMPLATE/package-lock.json
- hw6/_submissions/jung-hoyong/fibonacci/6-TEMPLATE/package.json
- hw6/_submissions/jung-hoyong/fibonacci/6-TEMPLATE/src/fibonacci.js
- hw6/_submissions/jung-hoyong/fibonacci/6-TEMPLATE/src/fibonacci.test.js
- hw6/_submissions/jung-hoyong/spinning/6-TEMPLATE/README.md
- hw6/_submissions/jung-hoyong/spinning/6-TEMPLATE/babel.config.js
- hw6/_submissions/jung-hoyong/spinning/6-TEMPLATE/package-lock.json
- hw6/_submissions/jung-hoyong/spinning/6-TEMPLATE/package.json
- hw6/_submissions/jung-hoyong/spinning/6-TEMPLATE/src/spinning.js
- hw6/_submissions/jung-hoyong/spinning/6-TEMPLATE/src/spinning.test.js
> hw6 solution

- hw6/_submissions/thayne-josh/fibonacci/README.md
- hw6/_submissions/thayne-josh/fibonacci/babel.config.js
- hw6/_submissions/thayne-josh/fibonacci/package-lock.json
- hw6/_submissions/thayne-josh/fibonacci/package.json
- hw6/_submissions/thayne-josh/fibonacci/src/fibonacci.js
- hw6/_submissions/thayne-josh/fibonacci/src/fibonacci.test.js
- hw6/_submissions/thayne-josh/spinning/README.md
- hw6/_submissions/thayne-josh/spinning/babel.config.js
- hw6/_submissions/thayne-josh/spinning/package-lock.json
- hw6/_submissions/thayne-josh/spinning/package.json
- hw6/_submissions/thayne-josh/spinning/src/spinning.js
- hw6/_submissions/thayne-josh/spinning/src/spinning.test.js
Completed fibonacci and spinning functions. 
For fibonacci, I created a while loop until steps was 0 and through each iteration I added the current number to the previous number.
In spinning, I split the string by each word and then if the word was 5 chars or longer then split that word into an array, reversed the array, and then joined the characters back.
> Josh Thayne finised hw6

- hw6/_submissions/hola-jacob/fibonacci/README.md
- hw6/_submissions/hola-jacob/fibonacci/babel.config.js
- hw6/_submissions/hola-jacob/fibonacci/package-lock.json
- hw6/_submissions/hola-jacob/fibonacci/package.json
- hw6/_submissions/hola-jacob/fibonacci/src/fibonacci.js
- hw6/_submissions/hola-jacob/fibonacci/src/fibonacci.test.js
- hw6/_submissions/hola-jacob/spinning/README.md
- hw6/_submissions/hola-jacob/spinning/babel.config.js
- hw6/_submissions/hola-jacob/spinning/package-lock.json
- hw6/_submissions/hola-jacob/spinning/package.json
- hw6/_submissions/hola-jacob/spinning/src/spinning.js
- hw6/_submissions/hola-jacob/spinning/src/spinning.test.js
> Finished hw6

- hw6/_submissions/smith-statler/fibonacci/README.md
- hw6/_submissions/smith-statler/fibonacci/babel.config.js
- hw6/_submissions/smith-statler/fibonacci/package-lock.json
- hw6/_submissions/smith-statler/fibonacci/package.json
- hw6/_submissions/smith-statler/fibonacci/src/fibonacci.js
- hw6/_submissions/smith-statler/fibonacci/src/fibonacci.test.js
- hw6/_submissions/smith-statler/spinning/README.md
- hw6/_submissions/smith-statler/spinning/babel.config.js
- hw6/_submissions/smith-statler/spinning/package-lock.json
- hw6/_submissions/smith-statler/spinning/package.json
- hw6/_submissions/smith-statler/spinning/src/spinning.js
- hw6/_submissions/smith-statler/spinning/src/spinning.test.js
I completed the fibonacci and spinning assignments and included comments in the code.
> Statler Smith HW 6

- hw5/_submissions/smith-statler/mumbling/README.md
- hw5/_submissions/smith-statler/mumbling/babel.config.js
- hw5/_submissions/smith-statler/mumbling/package-lock.json
- hw5/_submissions/smith-statler/mumbling/package.json
- hw5/_submissions/smith-statler/mumbling/src/mumbling.js
- hw5/_submissions/smith-statler/mumbling/src/mumbling.test.js
- hw5/_submissions/smith-statler/scramblies/README.md
- hw5/_submissions/smith-statler/scramblies/babel.config.js
- hw5/_submissions/smith-statler/scramblies/package-lock.json
- hw5/_submissions/smith-statler/scramblies/package.json
- hw5/_submissions/smith-statler/scramblies/src/scramblies.js
- hw5/_submissions/smith-statler/scramblies/src/scramblies.test.js
I completed the problems and added a few tests to both mumbling and scramblies.
> Statler Smith HW 5

- hw5/_submissions/hola-jacob/mumbling/README.md
- hw5/_submissions/hola-jacob/mumbling/babel.config.js
- hw5/_submissions/hola-jacob/mumbling/package-lock.json
- hw5/_submissions/hola-jacob/mumbling/package.json
- hw5/_submissions/hola-jacob/mumbling/src/mumbling.js
- hw5/_submissions/hola-jacob/mumbling/src/mumbling.test.js
- hw5/_submissions/hola-jacob/scramblies/README.md
- hw5/_submissions/hola-jacob/scramblies/babel.config.js
- hw5/_submissions/hola-jacob/scramblies/package-lock.json
- hw5/_submissions/hola-jacob/scramblies/package.json
- hw5/_submissions/hola-jacob/scramblies/src/scramblies.js
- hw5/_submissions/hola-jacob/scramblies/src/scramblies.test.js
Finished mumbling and scamblies
> Finished hw5

- hw5/_submissions/haines-josh/mumbling/README.md
- hw5/_submissions/haines-josh/mumbling/babel.config.js
- hw5/_submissions/haines-josh/mumbling/package-lock.json
- hw5/_submissions/haines-josh/mumbling/package.json
- hw5/_submissions/haines-josh/mumbling/src/mumbling.js
- hw5/_submissions/haines-josh/mumbling/src/mumbling.test.js
- hw5/_submissions/haines-josh/scramblies/README.md
- hw5/_submissions/haines-josh/scramblies/babel.config.js
- hw5/_submissions/haines-josh/scramblies/package-lock.json
- hw5/_submissions/haines-josh/scramblies/package.json
- hw5/_submissions/haines-josh/scramblies/src/scramblies.js
- hw5/_submissions/haines-josh/scramblies/src/scramblies.test.js
Thx @baileycoleman for the last piece of my scrambled eggs code. # teamlead.
> scrambled eggs on mumbly muffins

- hw5/_submissions/smith-matthew/mumbling/README.md
- hw5/_submissions/smith-matthew/mumbling/babel.config.js
- hw5/_submissions/smith-matthew/mumbling/package-lock.json
- hw5/_submissions/smith-matthew/mumbling/package.json
- hw5/_submissions/smith-matthew/mumbling/src/mumbling.js
- hw5/_submissions/smith-matthew/mumbling/src/mumbling.test.js
- hw5/_submissions/smith-matthew/scramblies/README.md
- hw5/_submissions/smith-matthew/scramblies/babel.config.js
- hw5/_submissions/smith-matthew/scramblies/package-lock.json
- hw5/_submissions/smith-matthew/scramblies/package.json
- hw5/_submissions/smith-matthew/scramblies/src/scramblies.js
- hw5/_submissions/smith-matthew/scramblies/src/scramblies.test.js
> Finished HW 5

- hw5/_submissions/fitzgerald-spencer/mumbling/README.md
- hw5/_submissions/fitzgerald-spencer/mumbling/babel.config.js
- hw5/_submissions/fitzgerald-spencer/mumbling/package-lock.json
- hw5/_submissions/fitzgerald-spencer/mumbling/package.json
- hw5/_submissions/fitzgerald-spencer/mumbling/src/mumbling.js
- hw5/_submissions/fitzgerald-spencer/mumbling/src/mumbling.test.js
- hw5/_submissions/fitzgerald-spencer/scramblies/README.md
- hw5/_submissions/fitzgerald-spencer/scramblies/babel.config.js
- hw5/_submissions/fitzgerald-spencer/scramblies/package-lock.json
- hw5/_submissions/fitzgerald-spencer/scramblies/package.json
- hw5/_submissions/fitzgerald-spencer/scramblies/src/scramblies.js
- hw5/_submissions/fitzgerald-spencer/scramblies/src/scramblies.test.js
Finished HW5. Was able to use the spread operator on my string and a splice method for one of the problems. It was kind of fun to see how those methods work in JS
> Fitzgerald spencer hw5

- hw4/_submissions/white-isaac/package-lock.json
- hw4/_submissions/white-isaac/unique-order/README.md
- hw4/_submissions/white-isaac/unique-order/babel.config.js
- hw4/_submissions/white-isaac/unique-order/package-lock.json
- hw4/_submissions/white-isaac/unique-order/package.json
- hw4/_submissions/white-isaac/unique-order/src/unique-order.js
- hw4/_submissions/white-isaac/unique-order/src/unique-order.test.js
- hw4/_submissions/white-isaac/zeroes/README.md
- hw4/_submissions/white-isaac/zeroes/babel.config.js
- hw4/_submissions/white-isaac/zeroes/package-lock.json
- hw4/_submissions/white-isaac/zeroes/package.json
- hw4/_submissions/white-isaac/zeroes/src/zeroes.js
- hw4/_submissions/white-isaac/zeroes/src/zeroes.test.js
I used test driven development to create both the zeroes and unique-order functions.
> White-Isaac-HW4

- hw4/_submissions/fitzgerald-spencer/unique-order/README.md
- hw4/_submissions/fitzgerald-spencer/unique-order/babel.config.js
- hw4/_submissions/fitzgerald-spencer/unique-order/package-lock.json
- hw4/_submissions/fitzgerald-spencer/unique-order/package.json
- hw4/_submissions/fitzgerald-spencer/unique-order/src/unique-order.js
- hw4/_submissions/fitzgerald-spencer/unique-order/src/unique-order.test.js
- hw4/_submissions/fitzgerald-spencer/zeroes/README.md
- hw4/_submissions/fitzgerald-spencer/zeroes/babel.config.js
- hw4/_submissions/fitzgerald-spencer/zeroes/package-lock.json
- hw4/_submissions/fitzgerald-spencer/zeroes/package.json
- hw4/_submissions/fitzgerald-spencer/zeroes/src/zeroes.js
- hw4/_submissions/fitzgerald-spencer/zeroes/src/zeroes.test.js
I got unique-order done quickly, but struggled with the zeroes problem. The filter function ended up being extremely helpful in solving that problem.
> Fitzgerald spencer

- hw4/_submissions/madsen-peter/unique-order/README.md
- hw4/_submissions/madsen-peter/unique-order/babel.config.js
- hw4/_submissions/madsen-peter/unique-order/package-lock.json
- hw4/_submissions/madsen-peter/unique-order/package.json
- hw4/_submissions/madsen-peter/unique-order/src/unique-order.js
- hw4/_submissions/madsen-peter/unique-order/src/unique-order.test.js
- hw4/_submissions/madsen-peter/zeroes/README.md
- hw4/_submissions/madsen-peter/zeroes/babel.config.js
- hw4/_submissions/madsen-peter/zeroes/package-lock.json
- hw4/_submissions/madsen-peter/zeroes/package.json
- hw4/_submissions/madsen-peter/zeroes/src/zeroes.js
- hw4/_submissions/madsen-peter/zeroes/src/zeroes.test.js
I've completed HW4 by creating tests first and then using loops to run through the arrays and sort/remove things as needed to return the correct arrays.
> Peter Madsen has completed HW4

- hw7/_submissions/fitzgerald-spencer/camel-case/README.md
- hw7/_submissions/fitzgerald-spencer/camel-case/babel.config.js
- hw7/_submissions/fitzgerald-spencer/camel-case/package-lock.json
- hw7/_submissions/fitzgerald-spencer/camel-case/package.json
- hw7/_submissions/fitzgerald-spencer/camel-case/src/camel-case.js
- hw7/_submissions/fitzgerald-spencer/camel-case/src/camel-case.test.js
- hw7/_submissions/fitzgerald-spencer/x-o/README.md
- hw7/_submissions/fitzgerald-spencer/x-o/babel.config.js
- hw7/_submissions/fitzgerald-spencer/x-o/package-lock.json
- hw7/_submissions/fitzgerald-spencer/x-o/package.json
- hw7/_submissions/fitzgerald-spencer/x-o/src/x-o.js
- hw7/_submissions/fitzgerald-spencer/x-o/src/x-o.test.js
> Fitzgerald spencer hw7

- hw7/_submissions/haines-josh/camel-case/README.md
- hw7/_submissions/haines-josh/camel-case/babel.config.js
- hw7/_submissions/haines-josh/camel-case/package-lock.json
- hw7/_submissions/haines-josh/camel-case/package.json
- hw7/_submissions/haines-josh/camel-case/src/camel-case.js
- hw7/_submissions/haines-josh/camel-case/src/camel-case.test.js
- hw7/_submissions/haines-josh/x-o/README.md
- hw7/_submissions/haines-josh/x-o/babel.config.js
- hw7/_submissions/haines-josh/x-o/package-lock.json
- hw7/_submissions/haines-josh/x-o/package.json
- hw7/_submissions/haines-josh/x-o/src/x-o.js
- hw7/_submissions/haines-josh/x-o/src/x-o.test.js
I did a difficult thing using codes! Call me a hackerman.
> Big hug, little hug, big kiss, little kiss

- hw7/_submissions/stennett-jordan/camel-case/README.md
- hw7/_submissions/stennett-jordan/camel-case/babel.config.js
- hw7/_submissions/stennett-jordan/camel-case/package-lock.json
- hw7/_submissions/stennett-jordan/camel-case/package.json
- hw7/_submissions/stennett-jordan/camel-case/src/camel-case.js
- hw7/_submissions/stennett-jordan/camel-case/src/camel-case.test.js
- hw7/_submissions/stennett-jordan/x-o/README.md
- hw7/_submissions/stennett-jordan/x-o/babel.config.js
- hw7/_submissions/stennett-jordan/x-o/package-lock.json
- hw7/_submissions/stennett-jordan/x-o/package.json
- hw7/_submissions/stennett-jordan/x-o/src/x-o.js
- hw7/_submissions/stennett-jordan/x-o/src/x-o.test.js
Camel case
I used a lot of splits, joins, and toUppers/toLowers to coerce the strings to be camel case
x-o
I used a dictionary as a frequency counter to keep track of the number of each character appeared in the word and compared the counter at the end.
> complete hw7

- hw7/_submissions/Merkley-Connor/camel-case/README.md
- hw7/_submissions/Merkley-Connor/camel-case/babel.config.js
- hw7/_submissions/Merkley-Connor/camel-case/package-lock.json
- hw7/_submissions/Merkley-Connor/camel-case/package.json
- hw7/_submissions/Merkley-Connor/camel-case/src/camel-case.js
- hw7/_submissions/Merkley-Connor/camel-case/src/camel-case.test.js
- hw7/_submissions/Merkley-Connor/x-o/README.md
- hw7/_submissions/Merkley-Connor/x-o/babel.config.js
- hw7/_submissions/Merkley-Connor/x-o/package-lock.json
- hw7/_submissions/Merkley-Connor/x-o/package.json
- hw7/_submissions/Merkley-Connor/x-o/src/x-o.js
- hw7/_submissions/Merkley-Connor/x-o/src/x-o.test.js
> Connor Merkley HW7

- hw7/_submissions/madsen-peter/camel-case/README.md
- hw7/_submissions/madsen-peter/camel-case/babel.config.js
- hw7/_submissions/madsen-peter/camel-case/package-lock.json
- hw7/_submissions/madsen-peter/camel-case/package.json
- hw7/_submissions/madsen-peter/camel-case/src/camel-case.js
- hw7/_submissions/madsen-peter/camel-case/src/camel-case.test.js
- hw7/_submissions/madsen-peter/x-o/README.md
- hw7/_submissions/madsen-peter/x-o/babel.config.js
- hw7/_submissions/madsen-peter/x-o/package-lock.json
- hw7/_submissions/madsen-peter/x-o/package.json
- hw7/_submissions/madsen-peter/x-o/src/x-o.js
- hw7/_submissions/madsen-peter/x-o/src/x-o.test.js
> Peter Madsen completed HW7

- hw6/_submissions/haddad-demitri/fibonacci/README.md
- hw6/_submissions/haddad-demitri/fibonacci/babel.config.js
- hw6/_submissions/haddad-demitri/fibonacci/package-lock.json
- hw6/_submissions/haddad-demitri/fibonacci/package.json
- hw6/_submissions/haddad-demitri/fibonacci/src/fibonacci.js
- hw6/_submissions/haddad-demitri/fibonacci/src/fibonacci.test.js
- hw6/_submissions/haddad-demitri/package-lock.json
- hw6/_submissions/haddad-demitri/spinning/README.md
- hw6/_submissions/haddad-demitri/spinning/babel.config.js
- hw6/_submissions/haddad-demitri/spinning/package-lock.json
- hw6/_submissions/haddad-demitri/spinning/package.json
- hw6/_submissions/haddad-demitri/spinning/src/spinning.js
- hw6/_submissions/haddad-demitri/spinning/src/spinning.test.js
- hw7/_submissions/haddad-demitri/camel-case/README.md
- hw7/_submissions/haddad-demitri/camel-case/babel.config.js
- hw7/_submissions/haddad-demitri/camel-case/package-lock.json
- hw7/_submissions/haddad-demitri/camel-case/package.json
- hw7/_submissions/haddad-demitri/camel-case/src/camel-case.js
- hw7/_submissions/haddad-demitri/camel-case/src/camel-case.test.js
- hw7/_submissions/haddad-demitri/x-o/README.md
- hw7/_submissions/haddad-demitri/x-o/babel.config.js
- hw7/_submissions/haddad-demitri/x-o/package-lock.json
- hw7/_submissions/haddad-demitri/x-o/package.json
- hw7/_submissions/haddad-demitri/x-o/src/x-o.js
- hw7/_submissions/haddad-demitri/x-o/src/x-o.test.js
last week I completed hw7, so I went back to complete hw6.
> HW6 Submission

- hw7/_submissions/smith-statler/camel-case/README.md
- hw7/_submissions/smith-statler/camel-case/babel.config.js
- hw7/_submissions/smith-statler/camel-case/package-lock.json
- hw7/_submissions/smith-statler/camel-case/package.json
- hw7/_submissions/smith-statler/camel-case/src/camel-case.js
- hw7/_submissions/smith-statler/camel-case/src/camel-case.test.js
- hw7/_submissions/smith-statler/x-o/README.md
- hw7/_submissions/smith-statler/x-o/babel.config.js
- hw7/_submissions/smith-statler/x-o/package-lock.json
- hw7/_submissions/smith-statler/x-o/package.json
- hw7/_submissions/smith-statler/x-o/src/x-o.js
- hw7/_submissions/smith-statler/x-o/src/x-o.test.js
I completed the exercises for homework 7. In doing so, I practiced using a function that has only one output with a descriptive name.
> Statler Smith HW7

- hw7/_submissions/Graham-William/camel-case/README.md
- hw7/_submissions/Graham-William/camel-case/babel.config.js
- hw7/_submissions/Graham-William/camel-case/package-lock.json
- hw7/_submissions/Graham-William/camel-case/package.json
- hw7/_submissions/Graham-William/camel-case/src/camel-case.js
- hw7/_submissions/Graham-William/camel-case/src/camel-case.test.js
- hw7/_submissions/Graham-William/x-o/README.md
- hw7/_submissions/Graham-William/x-o/babel.config.js
- hw7/_submissions/Graham-William/x-o/package-lock.json
- hw7/_submissions/Graham-William/x-o/package.json
- hw7/_submissions/Graham-William/x-o/src/x-o.js
- hw7/_submissions/Graham-William/x-o/src/x-o.test.js
I think I got this working. I identified what I was doing wrong with git that was causing my files to not upload properly.
> Graham william hw7

- hw8/_submissions/parr-josh/index.js
- hw9/_submissions/parr-josh/builder.ts
- hw9/_submissions/parr-josh/factory.ts
- hw9/_submissions/parr-josh/singleton.ts
> Parr josh hw8

- hw9/_submissions/hola-jacob/builder.ts
- hw9/_submissions/hola-jacob/factory.ts
- hw9/_submissions/hola-jacob/singleton.ts
Finished in class and added what was missing
> Finished hw9

- hw9/_submissions/magill-dallen/builder.ts
- hw9/_submissions/magill-dallen/factory.ts
- hw9/_submissions/magill-dallen/singleton.ts
> magill-dallen hw9

- hw9/_submissions/madsen-peter/builder.ts
- hw9/_submissions/madsen-peter/factory.ts
- hw9/_submissions/madsen-peter/singleton.ts
> Peter Madsen completed HW9

- hw9/_submissions/stennett-jordan/builder.ts
- hw9/_submissions/stennett-jordan/factory.ts
- hw9/_submissions/stennett-jordan/singleton.ts
I followed along to the beat of my own song bam bam bam doodaleedadooo (continue psychedelic interlude for several minutes then fadeaway).
> finish hw9

- hw9/_submissions/white-isaac/builder.ts
- hw9/_submissions/white-isaac/factory.ts
- hw9/_submissions/white-isaac/readme.md
- hw9/_submissions/white-isaac/singleton.ts
> White-isaac-hw9

- hw9/_submissions/fitzgerald-spencer/builder.ts
- hw9/_submissions/fitzgerald-spencer/factory.ts
- hw9/_submissions/fitzgerald-spencer/singleton.ts
Really cool to see the design patterns.
> Finished HW 9

- hw8/_submissions/smith-statler/functional-functions/README.md
- hw8/_submissions/smith-statler/functional-functions/index.js
> Statler Smith HW 8

- hw9/_submissions/smith-statler/builder.ts
- hw9/_submissions/smith-statler/factory.ts
- hw9/_submissions/smith-statler/singleton.ts
I followed along in class and made the classes
> Statler Smith HW9

- hw8/_submissions/niemann-michael/functional-functions/README.md
- hw8/_submissions/niemann-michael/functional-functions/index.js
> HW8 final try, hopefully this works

- hw8/_submissions/tucker-nicole/functional-functions/README.md
- hw8/_submissions/tucker-nicole/functional-functions/index.js
- hw8/_submissions/tucker-nicole/functional-functions/test.html
> Nicole hw8

- hw8/_submissions/jung-hoyong/index.js
> hw8 solution

- hw8/_submissions/parr-josh/index.js
- hw9/_submissions/parr-josh/builder.ts
- hw9/_submissions/parr-josh/factory.ts
- hw9/_submissions/parr-josh/singleton.ts
> Parr josh hw9

- hw8/_submissions/madsen-peter/index.js
I completed this homework assignment
> Peter Madsen completed hw 8

- hw8/_submissions/branden-clark/stennett-jordan/index.js
> finish hw8

- hw8/_submissions/hola-jacob/functional-functions/index.js
> Finished fun homework

- hw8/_submissions/fitzgerald-spencer/functional-functions/README.md
- hw8/_submissions/fitzgerald-spencer/functional-functions/index.js
Cool to see the higher-level functions of arrays in javascript.
> finished hw8

- hw8/_submissions/haines-josh/index.js
I was actually able to do this homework all by myself! Give me a gold star.
> Functional programming is slick, just like Branden and Patriks teaching style

- hw8/_submissions/white-isaac/functional-functions/README.md
- hw8/_submissions/white-isaac/functional-functions/index.js
Finished the homework. Did each problem using my own function and the built in functions.
> White_isaac_hw8
